name: efi22-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - libffi=3.4.2
  - libsqlite=3.39.4
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=3.0.5
  - pip=22.2.2
  - python=3.10.6
  - readline=8.1.2
  - setuptools=65.4.1
  - tk=8.6.12
  - tzdata=2022d
  - wheel=0.37.1
  - xz=5.2.6
  - ipykernel=6.15.2
  - cufflinks-py=0.17.3
  - rich=12.5.1
  - darts=0.2
  - openpyxl=3.0.10
